### ISSUE TITLE
您好，我已经测试了，确实可行

### ISSUE THREAD

**Issue by SimonXuku** [waynez/sibionic-watch#1]
您好，我测试了一下，确实可以将血糖数据发送给ns。但是还有一些问题。
1.ns的秘钥，要用sha1加密，如果明文的话可否添加强制sha1.
2.没有上升下降箭头.
3.最好是打包成apk或者ipa这样子可以在手机端直接运行。
再次感谢您的分享。

**Comment by SimonXuku** [comment]
涉及到的follow的id，以及token，抓包应该全部都能获取

**Comment by waynez** [comment]
Thanks for feedback.

1. NS api key, README里面有提到，需要提供hashed key
2. arrow已经有解决方案，测试完成后会发布
3. 暂时没有这方面的计划哈。如果是往手机端方向开发的话，那完全没有必要通过API绕一道，直接就hijack蓝牙去和设备通信了。这个项目目前没有移动端的计划

**Comment by SimonXuku** [comment]
明白了，感谢您的回复。

**Comment by waynez** [comment]
Fixed in b31d0a80909fc5a443c05c8739154e8917e06fc6
